# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      # 1. Run the linter & auto-fix standard rule violations
      - id: ruff-check
        args: [ --fix ]

      # 2. Run the formatter to enforce flawless drop-in Black styling
      - id: ruff-format
